# Generated by Django 2.1.4 on 2018-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
